osx_image: xcode10.1
language: generic
matrix:
  include:
    # - &xcode
    #   name: Xcode 10.3 / Swift 5.0
    #   os: osx
    #   osx_image: xcode10.3
    #   script:
    #     - ./test macos
    #     - ./test ios
    #     - ./test tvos
    # - &swiftpm_darwin
    #   name: SwiftPM / Darwin / Swift 5.0
    #   os: osx
    #   osx_image: xcode10.3
    #   script: ./test swiftpm
    - &swiftpm_linux
      name: SwiftPM / Linux / Swift 5.2.5
      os: linux
      dist: trusty
      sudo: required
      env:
        - SWIFT_VERSION=5.2.5
      install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
    - <<: *linux
      name: Linux / Swift 5.0 Development
      env:
        - SWIFT_VERSION=5.3-DEVELOPMENT-SNAPSHOT-2020-09-04-a
    - <<: *swiftpm_linux
      name: SwiftPM / Linux / Swift Development
      env:
        - SWIFT_VERSION=DEVELOPMENT-SNAPSHOT-2020-08-31-a
install: true
script:
  - ./test $TYPE

notifications:
  email: false
